### ISSUE TITLE
Realize the ergonomic exploration of time (N16)

### ISSUE THREAD

**Issue by EricBoix** [MEPP-team/RICT#7]
Refer to description of [Need 16](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need016.md)

- [x] The state of a (displayed) city at a given historical moment includes the city geometries of the city objects 
- [x] The user interaction (with the interface) in order to select an historical moment must be done with a slider (or with any interface element specifying an historical moment e.g. the media browser)
- [x] Within the interface the temporal mode is toggable (can be tuned On/Off)

**Comment by EricBoix** [comment]
For VJA:
 - Clean-up this issue by weeding out what was done.
 - Split the resulting content. 
 - Fan out the issues according to the milestone.

**Comment by jailln** [comment]
The [Need 16](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need016.md) has been broke down in two parts with different priorities (high and low). To answer this issue, only the high priorities items must be fulfilled:

* [x] When a media is selected within the media browser, an associated historical moment gets defined. The user can now ask to be warped to the location and at the corresponding moment (the time slider gets refreshed) within the geometrical view.
 * [x] The state of a (displayed) city at a given historical moment includes the city geometries of the city objects
 * [] The state of a (displayed) city at a given historical moment includes the attached information (e.g. the medias)
 * [x] The user interaction (with the interface) in order to select an historical moment must be done with a slider (or with any interface element specifying an historical moment e.g. the media browser)
 * [] Within the interface the temporal mode is toggable (can be tuned On/Off)

**Comment by EricBoix** [comment]
[Need 16](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need016.md) was updated to remove what was Vilo3D related (with a breakdown a [someday issue](https://github.com/MEPP-team/RICT/issues/29)

**Comment by EricBoix** [comment]
[PR #5](https://github.com/MEPP-team/UDV/pull/5) closes this issue.
